### ISSUE TITLE
Simplify `build` command line: accept target image metadata in a file

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/ansible-bender#10]
[Started by](https://github.com/TomasTomecek/ansible-bender/pull/9#discussion_r229684843)  @jcgruenhage.

My idea is to store the metadata in an ansible variable, the variable is a dict:
```yaml
- hosts: all
  vars:
    ansible_bender:
      base_image: fedora:28
      target_image:
        name: asdqwe
        environment:
          X: Y
        labels:
          ...
      working_container:
        user: 12345
        volumes:
        - { src: /path/to/my/code, dest: /src:Z }
tasks:
  ...
```

The main problem with this is that ab would need to read those variables, so they can't contain any jinja. Not sure if ansible is able to process them and output in some way. On the other hand, we could probably have an ansible plugin which would read those vars and then magically create and initiate the container.
